name: Integration Tests

on:
  repository_dispatch:
    types: [integration-test]

jobs:
  run-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hydephp/action@master
        with:
          debug: true
          upload-artifact: true
